openapi: 3.2.0
info:
  title: Overview Specific Shipper Accounts API
  version: '1.0'
  summary: API Overview
  contact:
    name: AfterShip Support
    url: https://www.aftership.com/contact-us
    email: support@aftership.com
  termsOfService: https://www.aftership.com/legal/terms-of-service
  description: '> OAS Schema can be downloaded [here](https://stoplight.io/api/v1/projects/automizely/docs-core-postmenapi-com/nodes/reference/api.v3.json?branch=master&deref=optimizedBundle)'
servers:
- description: Sandbox
  url: https://sandbox-api.aftership.com/postmen/v3
- url: https://api.aftership.com/postmen/v3
  description: Production
security:
- as-api-key: []
tags:
- name: Specific Shipper Accounts
paths:
  /couriers/fedex/shipper-accounts:
    parameters: []
    post:
      summary: Create a FedEx shipper account
      operationId: post-v3-couriers-fedex-shipper-accounts
      responses:
        '200':
          description: Create a FedEx or FedEx Ground® Economy shipper account
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  example-1:
                    meta:
                      code: 200
                      message: OK
                      details: []
                    data:
                      id: 00000000-0000-0000-0000-000000000000
                      description: My Shipper Account
                      slug: fedex
                      status: enabled
                      timezone: Asia/Hong_Kong
                      type: user
                      created_at: '2016-02-12T10:30:50+00:00'
                      updated_at: '2016-09-23T04:56:26+00:00'
                      address:
                        country: HKG
                        contact_name: Sir Foo
                        phone: '11111111'
                        fax: null
                        email: foo@foo.com
                        company_name: Foo Store
                        street1: Workshop A, 10/F, Wah Shing Industrial Building
                        street2: 18 Cheung Shun Street, Lai Chi Kok
                        city: Lai Chi Kok
                        type: business
                        postal_code: null
                        state: null
                        street3: null
                        tax_id: null
                properties:
                  meta:
                    $ref: '#/components/schemas/Meta.v3'
                  data:
                    type: object
                    x-stoplight:
                      id: 0l3adq18m6kir
                    properties:
                      id:
                        type: string
                        x-stoplight:
                          id: l6399y8cvu0oh
                        description: Shipper Account ID
                      address:
                        $ref: '#/components/schemas/Address.v3'
                        x-stoplight:
                          id: lz1k0e7j4hsgi
                        description: 'Address object: the description of address information'
                      slug:
                        type: string
                        x-stoplight:
                          id: 5y06213fs77dz
                        description: Couirer slug
                      status:
                        type: string
                        x-stoplight:
                          id: r7y62sxswkdua
                        enum:
                        - enabled
                        - disabled
                        - deleted
                      description:
                        type: string
                        x-stoplight:
                          id: 3wp361kj1kjwf
                        description: The description of the account
                      type:
                        type: string
                        x-stoplight:
                          id: z4abx0k3banyl
                        enum:
                        - default
                        - user
                        description: The type of the shipper_account
                      timezone:
                        type: string
                        x-stoplight:
                          id: knijyh5uvhvnb
                        description: Shipper account timezone
                      settings:
                        type: object
                        x-stoplight:
                          id: d81id3b6i3uhb
                        description: 'Settings object: additional settings of the shipper account.'
                        properties:
                          preferred_currency:
                            type: string
                            x-stoplight:
                              id: e7eyfy4kg9ng0
                          electronic_trade_documents_enabled:
                            type: boolean
                            x-stoplight:
                              id: mrxhsnjbo198h
                            description: Set to true to enable FedEx Electronic Trade Documents (ETD), provide both commercial_invoice_letterhead and commercial_invoice_signature are required. Otherwise ETD is disabled and any provided image fields are ignored.
                          commercial_invoice_letterhead:
                            type: string
                            x-stoplight:
                              id: mrxhsnjbo198h
                            description: Letterhead image to generate courier's electronic commercial invoice. Only Base64-encoded PNG images are supported, the max resolution is 700 pixels wide by 50 pixels long. Only applies to FedEx currently.
                          commercial_invoice_signature:
                            type: string
                            x-stoplight:
                              id: vdvo6u1y4iw09
                            description: Signature image to generate courier's electronic commercial invoice. Only Base64-encoded PNG images are supported, the max resolution is 240 pixels wide by 25 pixels long. Only applies to FedEx currently.
                      created_at:
                        type: string
                        x-stoplight:
                          id: cs8pqzct0grbz
                        description: A formatted date.
                      updated_at:
                        type: string
                        x-stoplight:
                          id: 269eik9j928ug
                        description: A formatted date.
              examples:
                example-1:
                  value:
                    meta:
                      code: 200
                      message: OK
                      details: []
                    data:
                      id: 00000000-0000-0000-0000-000000000000
                      description: My Shipper Account
                      slug: fedex
                      status: enabled
                      timezone: Asia/Hong_Kong
                      type: default
                      created_at: '2016-02-12T10:30:50+00:00'
                      updated_at: '2016-09-23T04:56:26+00:00'
                      address:
                        country: HKG
                        contact_name: Sir Foo
                        phone: '11111111'
                        fax: null
                        email: foo@foo.com
                        company_name: Foo Store
                        street1: Workshop A, 10/F, Wah Shing Industrial Building
                        street2: 18 Cheung Shun Street, Lai Chi Kok
                        city: Lai Chi Kok
                        type: business
                        postal_code: null
                        state: null
                        street3: null
                        tax_id: null
                      settings:
                        preferred_currency: USD
                        electronic_trade_documents_enabled: true
                        commercial_invoice_letterhead: '********'
                        commercial_invoice_signature: '********'
      description: 'This endpoint allows you to create your FedEx or FedEx Ground® Economy shipper account via API. You can integrate our API with your system and manage the shipper account according to your needs.


        Please ensure that your account credentials, invoice, address are correct.'
      parameters:
      - schema:
          type: string
          default: application/json
          example: application/json
        in: header
        name: Content-Type
        description: Content-Type
        required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                example-1:
                  slug: fedex
                  description: My Shipper Account
                  timezone: Asia/Hong_Kong
                  credentials:
                    account_number: '******'
                  invoice:
                    number: '234562278'
                    currency: USD
                    date: '2026-02-24'
                    amount: 234
                  settings:
                    preferred_currency: USD
                    electronic_trade_documents_enabled: true
                    commercial_invoice_letterhead: '********'
                    commercial_invoice_signature: '********'
                  address:
                    street1: Workshop A, 10/F, Wah Shing Industrial Building
                    country: HKG
                    contact_name: Sir Foo
                    phone: '11111111'
                    email: foo@foo.com
                    company_name: Foo Store
                    street2: 18 Cheung Shun Street, Lai Chi Kok
                    city: Lai Chi Kok
                    state: null
                    postal_code: null
                    type: business
                    tax_id: null
              required:
              - slug
              - description
              - credentials
              - address
              - invoice
              properties:
                slug:
                  type: string
                  enum:
                  - fedex
                  - fedex-smartpost
                description:
                  type: string
                timezone:
                  type: string
                credentials:
                  type: object
                  required:
                  - account_number
                  properties:
                    account_number:
                      type: string
                      x-stoplight:
                        id: b09506p7q48w7
                    hub_id:
                      type: string
                      x-stoplight:
                        id: iwadl2cjpc1l0
                      description: Required for FedEx Ground® Economy.
                address:
                  type: object
                  additionalProperties: false
                  description: 'Address object: the description of address information'
                  x-stoplight:
                    id: yxyjrpu0ejpdy
                  required:
                  - street1
                  - country
                  - contact_name
                  properties:
                    street1:
                      type: string
                      x-stoplight:
                        id: 5jwe58xjdd8nb
                      description: address_line1 of address
                    country:
                      type: string
                      x-stoplight:
                        id: bnh6ao7egflqp
                      description: Country in ISO 3166-1 alpha 3 code
                    contact_name:
                      type: string
                      x-stoplight:
                        id: jxo9m3gx37a8n
                      description: contact_name of address
                    phone:
                      type: string
                      x-stoplight:
                        id: 1sqa5he9quwvy
                      description: contact_phone of address
                    email:
                      type:
                      - string
                      - 'null'
                      x-stoplight:
                        id: bm9kfy2gchepq
                      description: email of address
                    company_name:
                      type:
                      - string
                      - 'null'
                      x-stoplight:
                        id: zmy6uepr9tcda
                      description: company_name of address
                    street2:
                      type:
                      - string
                      - 'null'
                      x-stoplight:
                        id: 2k0u00qvdlaj5
                      description: address_line2 of address
                    city:
                      type:
                      - string
                      - 'null'
                      x-stoplight:
                        id: 0vl4z3l1k4svl
                      description: city of address
                    state:
                      type:
                      - string
                      - 'null'
                      x-stoplight:
                        id: i3fdfnsqe8jqq
                      description: state of address
                    postal_code:
                      type:
                      - string
                      - 'null'
                      x-stoplight:
                        id: co72zwed6ql97
                      description: postal_code of address
                    type:
                      x-stoplight:
                        id: wq8micfzwkikg
                      description: type of address
                      type:
                      - string
                      - 'null'
                      enum:
                      - residential
                      - business
                    tax_id:
                      type:
                      - string
                      - 'null'
                      x-stoplight:
                        id: k0ptjvja7yxps
                      description: tax id
                invoice:
                  type: object
                  x-stoplight:
                    id: wfq7t4an0gmmo
                  required:
                  - number
                  - currency
                  - date
                  - amount
                  properties:
                    number:
                      type: string
                      description: Unique invoice identifier or reference number.
                      x-stoplight:
                        id: brso04e6y64ls
                    currency:
                      type: string
                      description: ISO currency code for the invoice amount (e.g. USD).
                      x-stoplight:
                        id: rygqbgzlfjhow
                    date:
                      type: string
                      description: Invoice date in YYYY-MM-DD format.
                      x-stoplight:
                        id: dllkna2fi5xvt
                    amount:
                      type: number
                      x-stoplight:
                        id: 0vjrx5zlnl0hu
                      description: 'Total amount on the commercial invoice. '
                settings:
                  type: object
                  description: 'Settings object: additional settings of the shipper account.'
                  properties:
                    preferred_currency:
                      type: string
                      x-stoplight:
                        id: fsawk2usov9mg
                    electronic_trade_documents_enabled:
                      type: string
                      description: Set to true to enable FedEx Electronic Trade Documents (ETD), provide both commercial_invoice_letterhead and commercial_invoice_signature are required. Otherwise ETD is disabled and any provided image fields are ignored.
                    commercial_invoice_letterhead:
                      type: string
                      description: Letterhead image to generate courier's electronic commercial invoice. Only Base64-encoded PNG images are supported, the max resolution is 700 pixels wide by 50 pixels long. Only applies to FedEx currently.
                    commercial_invoice_signature:
                      type: string
                      description: Signature image to generate courier's electronic commercial invoice. Only Base64-encoded PNG images are supported, the max resolution is 240 pixels wide by 25 pixels long. Only applies to FedEx currently.
            examples:
              example-1:
                value:
                  slug: fedex
                  description: My Shipper Account
                  timezone: Asia/Hong_Kong
                  credentials:
                    account_number: '******'
                  invoice:
                    number: '234562278'
                    currency: USD
                    date: '2026-02-24'
                    amount: 234
                  settings:
                    preferred_currency: USD
                    electronic_trade_documents_enabled: true
                    commercial_invoice_letterhead: '********'
                    commercial_invoice_signature: '********'
                  address:
                    street1: Workshop A, 10/F, Wah Shing Industrial Building
                    country: HKG
                    contact_name: Sir Foo
                    phone: '11111111'
                    email: foo@foo.com
                    company_name: Foo Store
                    street2: 18 Cheung Shun Street, Lai Chi Kok
                    city: Lai Chi Kok
                    state: null
                    postal_code: null
                    type: business
                    tax_id: null
          application/xml:
            schema:
              type: object
              properties: {}
        description: Create a FedEx or FedEx Ground® Economy shipper account
      tags:
      - Specific Shipper Accounts
      security:
      - as-api-key: []
      x-stoplight:
        id: c1hmaoymtcjf2
  /couriers/fedex/shipper-accounts/{id}/update:
    parameters:
    - schema:
        type: string
      name: id
      in: path
      required: true
    post:
      summary: Update a FedEx shipper account
      operationId: post-v3-couriers-fedex-shipper-accounts-id-update
      responses:
        '200':
          description: Update a FedEx or FedEx Ground® Economy shipper account
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  example-1:
                    meta:
                      code: 200
                      message: OK
                      details: []
                    data:
                      id: 00000000-0000-0000-0000-000000000000
                      description: My Shipper Account
                      slug: fedex
                      status: enabled
                      timezone: Asia/Hong_Kong
                      type: user
                      created_at: '2016-02-12T10:30:50+00:00'
                      updated_at: '2016-09-23T04:56:26+00:00'
                      address:
                        country: HKG
                        contact_name: Sir Foo
                        phone: '11111111'
                        fax: null
                        email: foo@foo.com
                        company_name: Foo Store
                        street1: Workshop A, 10/F, Wah Shing Industrial Building
                        street2: 18 Cheung Shun Street, Lai Chi Kok
                        city: Lai Chi Kok
                        type: business
                        postal_code: null
                        state: null
                        street3: null
                        tax_id: null
                properties:
                  meta:
                    $ref: '#/components/schemas/Meta.v3'
                  data:
                    type: object
                    x-stoplight:
                      id: 0l3adq18m6kir
                    properties:
                      id:
                        type: string
                        x-stoplight:
                          id: l6399y8cvu0oh
                        description: Shipper Account ID
                      address:
                        $ref: '#/components/schemas/Address.v3'
                        x-stoplight:
                          id: lz1k0e7j4hsgi
                        description: 'Address object: the description of address information'
                      slug:
                        type: string
                        x-stoplight:
                          id: 5y06213fs77dz
                        description: Couirer slug
                      status:
                        type: string
                        x-stoplight:
                          id: r7y62sxswkdua
                        enum:
                        - enabled
                        - disabled
                        - deleted
                      description:
                        type: string
                        x-stoplight:
                          id: 3wp361kj1kjwf
                        description: The description of the account
                      type:
                        type: string
                        x-stoplight:
                          id: z4abx0k3banyl
                        enum:
                        - default
                        - user
                        description: The type of the shipper_account
                      timezone:
                        type: string
                        x-stoplight:
                          id: knijyh5uvhvnb
                        description: Shipper account timezone
                      settings:
                        type: object
                        x-stoplight:
                          id: d81id3b6i3uhb
                        description: 'Settings object: additional settings of the shipper account.'
                        properties:
                          preferred_currency:
                            type: string
                            x-stoplight:
                              id: e7eyfy4kg9ng0
                          electronic_trade_documents_enabled:
                            type: 'true'
                            x-stoplight:
                              id: mrxhsnjbo198h
                            description: Set to true to enable FedEx Electronic Trade Documents (ETD), provide both commercial_invoice_letterhead and commercial_invoice_signature are required. Otherwise ETD is disabled and any provided image fields are ignored.
                          commercial_invoice_letterhead:
                            type: string
                            x-stoplight:
                              id: mrxhsnjbo198h
                            description: Letterhead image to generate courier's electronic commercial invoice. Only Base64-encoded PNG images are supported, the max resolution is 700 pixels wide by 50 pixels long. Only applies to FedEx currently.
                          commercial_invoice_signature:
                            type: string
                            x-stoplight:
                              id: vdvo6u1y4iw09
                            description: Signature image to generate courier's electronic commercial invoice. Only Base64-encoded PNG images are supported, the max resolution is 240 pixels wide by 25 pixels long. Only applies to FedEx currently.
                      created_at:
                        type: string
                        x-stoplight:
                          id: cs8pqzct0grbz
                        description: A formatted date.
                      updated_at:
                        type: string
                        x-stoplight:
                          id: 269eik9j928ug
                        description: A formatted date.
              examples:
                example-1:
                  value:
                    meta:
                      code: 200
                      message: OK
                      details: []
                    data:
                      id: 00000000-0000-0000-0000-000000000000
                      description: My Shipper Account
                      slug: fedex
                      status: enabled
                      timezone: Asia/Hong_Kong
                      type: default
                      created_at: '2016-02-12T10:30:50+00:00'
                      updated_at: '2016-09-23T04:56:26+00:00'
                      address:
                        country: HKG
                        contact_name: Sir Foo
                        phone: '11111111'
                        fax: null
                        email: foo@foo.com
                        company_name: Foo Store
                        street1: Workshop A, 10/F, Wah Shing Industrial Building
                        street2: 18 Cheung Shun Street, Lai Chi Kok
                        city: Lai Chi Kok
                        type: business
                        postal_code: null
                        state: null
                        street3: null
                        tax_id: null
                      settings:
                        preferred_currency: USD
                        electronic_trade_documents_enabled: true
                        commercial_invoice_letterhead: '********'
                        commercial_invoice_signature: '********'
      description: "This endpoint allows you to update a legacy FedEx or FedEx Ground® Economy shipper account via API. You can integrate our API with your system and manage the shipper account according to your needs. \n\nOnce the update is completed, the account credentials and address information will be locked and cannot be modified. Please ensure that your account credentials, invoice details, and address are correct before initiating the update."
      parameters:
      - schema:
          type: string
          default: application/json
          example: application/json
        in: header
        name: Content-Type
        description: Content-Type
        required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                example-1:
                  credentials:
                    account_number: '******'
                  invoice:
                    number: '234562278'
                    currency: USD
                    date: '2026-02-24'
                    amount: 234
                  settings:
                    preferred_currency: USD
                    electronic_trade_documents_enabled: true
                    commercial_invoice_letterhead: '********'
                    commercial_invoice_signature: '********'
                  address:
                    street1: Workshop A, 10/F, Wah Shing Industrial Building
                    country: HKG
                    contact_name: Sir Foo
                    phone: '11111111'
                    email: foo@foo.com
                    company_name: Foo Store
                    street2: 18 Cheung Shun Street, Lai Chi Kok
                    city: Lai Chi Kok
                    state: null
                    postal_code: null
                    type: business
                    tax_id: null
              required:
              - invoice
              properties:
                invoice:
                  type: object
                  required:
                  - number
                  - currency
                  - date
                  - amount
                  properties:
                    number:
                      type: string
                      description: Unique invoice identifier or reference number.
                    currency:
                      type: string
                      description: ISO currency code for the invoice amount (e.g. USD).
                    date:
                      type: string
                      description: Invoice date in YYYY-MM-DD format.
                    amount:
                      type: number
                      description: 'Total amount on the commercial invoice. '
                credentials:
                  type: object
                  required:
                  - account_number
                  properties:
                    account_number:
                      type: string
                    hub_id:
                      type: string
                      description: Required for FedEx Ground® Economy.
                address:
                  type: object
                  additionalProperties: false
                  description: 'Address object: the description of address information'
                  required:
                  - street1
                  - country
                  - contact_name
                  properties:
                    street1:
                      type: string
                      description: address_line1 of address
                    country:
                      type: string
                      description: Country in ISO 3166-1 alpha 3 code
                    contact_name:
                      type: string
                      description: contact_name of address
                    phone:
                      type: string
                      description: contact_phone of address
                    email:
                      type:
                      - string
                      - 'null'
                      description: email of address
                    company_name:
                      type:
                      - string
                      - 'null'
                      description: company_name of address
                    street2:
                      type:
                      - string
                      - 'null'
                      description: address_line2 of address
                    city:
                      type:
                      - string
                      - 'null'
                      description: city of address
                    state:
                      type:
                      - string
                      - 'null'
                      description: state of address
                    postal_code:
                      type:
                      - string
                      - 'null'
                      description: postal_code of address
                    type:
                      description: type of address
                      type:
                      - string
                      - 'null'
                      enum:
                      - residential
                      - business
                    tax_id:
                      type:
                      - string
                      - 'null'
                      description: tax id
                settings:
                  type: object
                  description: 'Settings object: additional settings of the shipper account.'
                  properties:
                    preferred_currency:
                      type: string
                    electronic_trade_documents_enabled:
                      type: boolean
                      description: Set to true to enable FedEx Electronic Trade Documents (ETD), provide both commercial_invoice_letterhead and commercial_invoice_signature are required. Otherwise ETD is disabled and any provided image fields are ignored.
                    commercial_invoice_letterhead:
                      type: string
                      description: Letterhead image to generate courier's electronic commercial invoice. Only Base64-encoded PNG images are supported, the max resolution is 700 pixels wide by 50 pixels long. Only applies to FedEx currently.
                    commercial_invoice_signature:
                      type: string
                      description: Signature image to generate courier's electronic commercial invoice. Only Base64-encoded PNG images are supported, the max resolution is 240 pixels wide by 25 pixels long. Only applies to FedEx currently.
            examples:
              example-1:
                value:
                  credentials:
                    account_number: '******'
                  invoice:
                    number: '234562278'
                    currency: USD
                    date: '2026-02-24'
                    amount: 234
                  settings:
                    preferred_currency: USD
                    electronic_trade_documents_enabled: true
                    commercial_invoice_letterhead: '********'
                    commercial_invoice_signature: '********'
                  address:
                    street1: Workshop A, 10/F, Wah Shing Industrial Building
                    country: HKG
                    contact_name: Sir Foo
                    phone: '11111111'
                    email: foo@foo.com
                    company_name: Foo Store
                    street2: 18 Cheung Shun Street, Lai Chi Kok
                    city: Lai Chi Kok
                    state: null
                    postal_code: null
                    type: business
                    tax_id: null
          application/xml:
            schema:
              type: object
              properties: {}
        description: Update a FedEx or FedEx Ground® Economy shipper account
      tags:
      - Specific Shipper Accounts
      security:
      - as-api-key: []
      x-stoplight:
        id: alkwtehrfwa1s
components:
  schemas:
    Address.v3:
      type: object
      x-stoplight:
        id: c01e28f80783b
      x-examples:
        example-1:
          country: HKG
          contact_name: Sir Foo
          phone: '11111111'
          fax: +1 206-654-3100
          email: foo@foo.com
          company_name: Foo Store
          street1: Workshop A, 10/F, Wah Shing Industrial Building
          street2: 18 Cheung Shun Street, Lai Chi Kok
          city: Lai Chi Kok
          type: business
          postal_code: null
          state: null
          street3: null
          tax_id: null
      title: Address
      description: 'Address object: the description of address information'
      x-tags:
      - Primitive
      examples: []
      required:
      - street1
      - country
      - contact_name
      properties:
        street1:
          type: string
          description: 'address_line1 of address

            '
        country:
          type: string
          description: Country in ISO 3166-1 alpha 3 code
        contact_name:
          type: string
          description: contact_name of address
        phone:
          type: string
          description: contact_phone of address
        fax:
          type:
          - string
          - 'null'
          description: fax_number of address
        email:
          type:
          - string
          - 'null'
          description: email of address
        company_name:
          type:
          - string
          - 'null'
          description: company_name of address
        street2:
          type:
          - string
          - 'null'
          description: address_line2 of address
        street3:
          type:
          - string
          - 'null'
          description: address_line3 of address
        city:
          type:
          - string
          - 'null'
          description: city of address
        state:
          type:
          - string
          - 'null'
          description: state of address
        postal_code:
          type:
          - string
          - 'null'
          description: postal_code of address
        type:
          type:
          - string
          - 'null'
          description: type of address
          enum:
          - residential
          - business
        tax_id:
          type:
          - string
          - 'null'
          description: tax id
        tax_id_type:
          type:
          - string
          - 'null'
          description: 'tax id type. Only applies to DHL Express, DHL eCommerce US, DHL eCommerce UK.

            - vat: Value-Added tax

            - gst: Goods and Service Tax

            - eori: European Union Registration and Identification

            - ioss: Import One Stop Shop

            - pan: Pan-Aarav

            - ukims: UK Internal Market Scheme

            - other: Other

            '
          x-stoplight:
            id: 7rtl96ei81zeb
          enum:
          - vat
          - gst
          - eori
          - ioss
          - pan
          - ukims
          - other
        identification_number:
          type:
          - string
          - 'null'
          description: identification number
          x-stoplight:
            id: u1nqwj1dvhw67
        identification_type:
          type:
          - string
          - 'null'
          description: 'identification type

            - mil: Military Number

            - nid: National Identity Card

            - pas: Passport

            - other: Other'
          x-stoplight:
            id: gh9ttmhi0xmik
          enum:
          - mil
          - nid
          - pas
          - other
        eori_number:
          type:
          - string
          - 'null'
          description: eori number
        location:
          type:
          - object
          - 'null'
          properties:
            lat:
              type: number
              description: latitude number
            lng:
              type: number
              description: longitude number
    Meta.v3:
      description: Meta data object.
      type: object
      x-examples: {}
      examples:
      - code: 200
        type: OK
        message: Everything worked as expected.
      title: Meta
      x-tags:
      - Envelope
      properties:
        code:
          type: integer
          description: Code of Meta
        message:
          type: string
          description: Message of Meta
        details:
          type: array
          description: Details of Meta
          items:
            $ref: '#/components/schemas/Error.v3'
        retryable:
          type: boolean
          description: Whether this request will be retryable or not
      required:
      - code
      - message
    Error.v3:
      type: object
      title: Error
      description: Each error object contains a "path" key and an "info" key. The "path" is the JSON path of the request object to indicate the error location. The "info" is a human-readable description of the error.
      examples:
      - path: data.shipment.ship_from.country
        info: data.shipment.ship_from.country is a required property
      additionalProperties: false
      x-tags:
      - Envelope
      properties:
        path:
          type: string
          description: The json path of the request object to indicate the error location
          example: account.email
        info:
          type: string
          description: A human-readable description of the error.
          example: account.email is invalid
  securitySchemes:
    as-api-key:
      name: as-api-key
      type: apiKey
      in: header
